name: Links Check

on:
  push:
  pull_request:

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose README.md docs/**/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
